export const TEST_REDUCER = 'TEST_REDUCER'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REGISTRATION_SUCCESS  = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const CURRENT_ROUTE = 'CURRENT_ROUTE';
export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';